modules/educacion/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^(?P<pk>[0-9]+)/$',contenido, name="contenido"),
    url(r'^categoria/(?P<pk>[a-zA-Z]+)/$', contenido_categoria, name="contenido_categoria"),
    url(r'^busqueda/$', contenido_busqueda, name="contenido_busqueda"),
    url(r'^cursos/$', cursos, name="cursos"),
    url(r'^cursos/(?P<pk>[0-9]+)/$', cursos_ver, name="cursos"),
    url(r'^cursos/agregar/$', cursos_agregar, name="cursos_agregar"),
    url(r'^cursos/agregar/(?P<pk>[0-9]+)/$', cursos_registrar, name="curso_registrar"),
    url(r'^cursos/eliminar/(?P<pk>[0-9]+)/$', cursos_eliminar, name="curso_eliminar"),
]

modules/landing/urls.py
from django.conf.urls import url
from .views import index, dashboard, login, signup, logout

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^dashboard/$', dashboard, name="dashboard"),
    url(r'^login/$', login, name="login"),
    url(r'^signup/$', signup, name="signup"),
    url(r'^logout/$', logout, name="logout"),
]

modules/tracking/urls.py
from django.conf.urls import url
from .views import agregarTransaccion, agregarCuenta, misTransacciones,misCuentas, subirTicket

urlpatterns = [
    url(r'^transaccion/$', agregarTransaccion, name="transaccion"),
    url(r'^nuevacuenta/$', agregarCuenta, name="cuenta"),
    url(r'^transacciones/$', misTransacciones, name="transacciones"),
    url(r'^cuentas/$', misCuentas, name="cuentas"),
    url(r'^ticket/$', subirTicket, name="ticket"),
]

trefi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('modules.landing.urls', namespace="landing")),
    url(r'^educacion/', include('modules.educacion.urls', namespace="educacion")),
    url(r'^', include('modules.tracking.urls', namespace="tracking")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_dash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}

    {% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'dashboard/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'dashboard/css/sb-admin.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'dashboard/css/plugins/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'dashboard/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="{% url 'landing:dashboard' %}"> <img src="{% static 'landing/img/Logo.png' %}" alt="Trefi" width=74 height=30></a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="{% url 'tracking:transaccion' %}">¿Ya registraste tus gastos hoy?🙄 <span class="label label-success">1</span></a>
                        </li>
                        <li>
                            <a href="{% url 'educacion:index' %}">¡Aprende a ahorrar!🤓 <span class="label label-warning">1</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">Ver todas</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{request.user.nombre}} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'landing:dashboard' %}"><i class="fa fa-fw fa-dashboard"></i> Mis tracking</a>
                        </li>
                        <li>
                            <a href="{% url 'educacion:index' %}"><i class="fa fa-fw fa-book"></i> Mis cursos</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Configuración</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{% url 'landing:logout' %}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="{% url 'educacion:index' %}"><i class="fa fa-fw fa-book"></i> Mis cursos</a>
                    </li>
                    <li>
                        <a href="{% url 'landing:dashboard' %}"><i class="fa fa-fw fa-dashboard"></i> Mi tracking</a>
                    </li>
                    <li>
                        <a href="{% url 'tracking:cuenta' %}"><i class="fa fa-fw fa-check-square-o"></i>Nueva Cuenta</a>
                    </li>
                    <li>
                        <a href="{% url 'tracking:transaccion' %}"><i class="fa fa-fw fa-edit"></i>Nueva Transacción</a>
                    </li>
                    <li>
                        <a href="{% url 'tracking:cuentas' %}"><i class="fa fa-fw fa-inbox"></i> Mis cuentas</a>
                    </li>
                    <li>
                        <a href="{% url 'tracking:transacciones' %}"><i class="fa fa-fw fa-money"></i> Mis transacciones</a>
                    </li>
                    <li>
                        <a href="forms.html"><i class="fa fa-fw fa-edit"></i> Tickets</a>
                    </li>
                    <li>
                        <a href="bootstrap-elements.html"><i class="fa fa-fw fa-desktop"></i> Mis logros</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            {% block content %}

            {% endblock %}
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'dashboard/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
    <!-- Morris Charts JavaScript -->
    <script src="{% static 'dashboard/js/plugins/morris/raphael.min.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/morris/morris.min.js' %}"></script>
    <!--script src="{% static 'dashboard/js/plugins/morris/morris-data.js' %}"></script-->

    <script src="{% static 'dashboard/js/plugins/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/flot/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/flot/flot-data.js' %}"></script>
    {%block js %}
    {% endblock %}

</body>

</html>

templates/base_educacion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mis Cursos</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'educacion/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'educacion/css/blog-home.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Temporary navbar container fix -->
    <style>
    .navbar-toggler {
        z-index: 1;
    }

    @media (max-width: 576px) {
        nav > .container {
            width: 100%;
        }
    }
    </style>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container">
            <a class="navbar-brand" href="#"><img src="{% static 'landing/img/Logo.png' %}" alt="Trefi" width=74 height=30></a>
            <div class="collapse navbar-collapse" id="navbarExample">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'landing:dashboard' %}"><i class="fa fa-fw fa-dashboard"></i> Mi tracking </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'landing:logout' %}"><i class="fa fa-fw fa-power-off"></i> Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="row">

            {% block content %}

            {% endblock %}

            <!-- Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Search Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Búsqueda</h5>
                    <form id="search" action="/educacion/busqueda/" method="GET"></form>
                        <div class="card-block">
                            <div class="input-group">
                                <input type="text" name="q" class="form-control" placeholder="Búsqueda...">
                                <span id="btn-search" class="input-group-btn">
                                    <button class="btn btn-secondary" type="button">Ir!</button>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>

                <!-- Categories Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Categorías</h5>
                    <div class="card-block">
                        <div class="row">
                            <div class="col-lg-6">
                                <ul class="list-unstyled mb-0">
                                    {% for key, value in categoria.items %}
                                    <li><a href="/educacion/categoria/{{key}}">{{value}}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>

                <!-- Side Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Mis cursos</h5>
                    <div class="card-block">
                        <a href="{% url 'educacion:cursos' %}" class="btn btn primary">Ver mis cursos</a>
                        <a href="{% url 'educacion:cursos_agregar' %}" class="btn btn primary">Agregar</a>
                    </div>
                </div>

            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-inverse">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Trefi 2017</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'educacion/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'educacion/vendor/tether/tether.min.js' %}"></script>
    <script src="{% static 'educacion/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <script>
        $( "#btn-search" ).click(function() {
            $( "#search" ).submit();
        });
    </script>
</body>

</html>