modules/landing/urls.py
from django.conf.urls import url
from .views import index, dashboard, login, signup, logout

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^dashboard/$', dashboard, name="dashboard"),
    url(r'^login/$', login, name="login"),
    url(r'^signup/$', signup, name="signup"),
    url(r'^logout/$', logout, name="logout"),
]

trefi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('modules.landing.urls', namespace="landing")),
    url(r'^educacion/', include('modules.educacion.urls', namespace="educacion")),
    url(r'^', include('modules.tracking.urls', namespace="tracking")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modules/landing/forms.py
from django import forms
from django.forms import  ModelForm

class SignupForm(forms.Form):

    email = forms.EmailField(
        max_length=100,
        widget=forms.EmailInput(
            attrs={
                "class":"form-control",
                "placeholder":"email"
            }
        ))

    password  = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(
            attrs={
                "class":"form-control",
                "placeholder":"password"
            }
        ))

    confirm_password  = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(
            attrs={
                "class":"form-control",
                "placeholder":"confirm password"
            }
        ))

    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

class LoginForm(forms.Form):

    email = forms.EmailField(
        max_length=100,
        widget=forms.EmailInput(
            attrs={
                "class":"form-control",
                "placeholder":"email"
            }
        ))

    password  = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(
            attrs={
                "class":"form-control",
                "placeholder":"password"
            }
        ))

modules/landing/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm,LoginForm
#from django.contrib.auth.models import User #Modelo de usuario default Django
from modules.users.models import User
from django.contrib.auth import authenticate,logout as logout_app,login as login_app #Pseudonimos para que no se confunda con el nombre de la funcion
from django.http import HttpResponse
from modules.tracking.functions import Balance,SaldoIngresos,SaldoGastos,SaldoMetas,TransLine, BalanceChart,GastosChart
from modules.tracking.models import Transaccion
from modules.tracking.models import TRANSACCIONES
import json
def index(request):
    form_login = LoginForm(request.POST or None)
    form_signup = SignupForm(request.POST or None)
    return render(request, "landing/index.html", {
        "form_login":form_login,
        "form_signup":form_signup,
        })

def dashboard(request):
    dummy_data  = [{
        'periodo':'2017 Q1',
        'Ingreso':2300,
        'Gasto':1500
    },{
        'periodo':'2017 Q2',
        'Ingreso':1700,
        'Gasto':1000
    },
    {
        'periodo':'2017 Q3',
        'Ingreso':2800,
        'Gasto':1900
    }]
    #print(TransLine())
    #print(BalanceChart(request.user))
    transacciones = Transaccion.objects.filter(usuario=request.user)[:10]
    return render(request, "dashboard/index.html",
        {'balance':Balance(request.user),
        'saldoMetas':SaldoMetas(request.user),
        'saldoIngresos':SaldoIngresos(request.user),
        'saldoGastos':SaldoGastos(request.user),
        'transacciones':transacciones,
        'dummy':dummy_data,
        'transdict':dict(TRANSACCIONES),
        'balancechart':BalanceChart(request.user),
        'gastoschart':GastosChart(request.user),
        })

#Tres funciones para autenticacion de usuario: Signup, Login y Logout
def login(request):
    form = LoginForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = authenticate(
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password']
                )
            if user is not None:
                login_app(request,user)
                return redirect('landing:dashboard')
            else:
                return HttpResponse("Usuario no encontrado")

    return render(request,'landing/index.html', {"login":form})

def signup(request):
    form = SignupForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.cleaned_data.pop('confirm_password', None)
            user = User.objects.create_user(**form.cleaned_data)
            return redirect("landing:dashboard")

    return render(request,'landing/index.html',{'sign':form})

def logout(request):
    logout_app(request)
    return redirect("landing:index")

templates/landing/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>trefi</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'landing/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'landing/css/landing-page.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'landing/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style media="screen">
        .img-responsive{margin: 0 auto;}
    </style>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#"> <img src="{% static 'landing/img/Logo.png' %}" alt="Trefi" width=74 height=30></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">Nosotros</a>
                    </li>
                    <li>
                        <a href="#services">Servicios</a>
                    </li>
                    <li>
                        <a href="#login">Log in</a>
                    </li>
                    <li>
                        <a href="#signup">Sign up</a>
                    </li>
                    <li>
                        <a href="#contact">Contacto</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message text-center">
                        <h1><img src="{% static 'landing/img/Logo.png' %}" alt="Trefi" align="center" width=490 height=200 class="img-responsive"></h1>
                        <h3>💵 Cuidar tus finanzas nunca fue tan fácil 😉</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <li>
                                <a href="https://github.com/jonatan-castaneda/trefi" class="btn btn-default btn-lg" target="_blank"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <li>
                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

	<a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">¿No sabes a dónde se va tu quincena? 😱 ¿te gustaría ahorrar?<br>¡Te enseñamos cómo! 🙋🏻‍</h2>
                    <p class="lead">Con Trefi te enseñamos todo sobre el manejo de tus finanzas para nunca más llegues rayando a fin de mes. 🏃🏽 Todo el poder del ahorro en la palma de tu mano.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="{% static 'landing/img/ayuda_ahorro.jpg' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">¡No vuelvas a olvidar un solo gasto! Toma el control de tus finanzas. 📋</h2>
                    <p class="lead">Trefi te ofrece herramientas para administrar tus gastos e ingresos 💸, para que apliques todo lo que te enseñamos.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="{% static 'landing/img/Tips.jpg' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Cumple con tus metas 🏄🏼<br>aprendiendo a manejar tu dinero.</h2>
                    <p class="lead">Con trefi es más fácil cumplir con tus logros financieros. Te llevaremos de la mano con cada una de tus metas para que obtengas resultados fácil y rápido. 💪🏾</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="{% static 'landing/img/metas.jpg' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>

    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">No te quedes con los <i>tips</i>, 🙄<br>¡Compártelos con tus amigos!</h2>
                    <p class="lead">Puedes compartir tus logros en nuestra red social para que las personas vean lo mejor de ti. 👩🏻‍🎨 Felicita a tus amigos por sus viaje a la playa y conciertos. 🏖</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="{% static 'landing/img/logros.jpg' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>

    <!-- Sign in -->
    <a  name="login"></a>
    <div class="content-section-a">

        <div class="container">
            <form action="{% url 'landing:login' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Login</h2>
                    Email: {{form_signup.email}}
                    Contraseña: {{form_login.password}}
                    <br>
                    <input type="submit" class="btn btn-primary" value="Login">
                </div>

            </div>
            </form>

        </div>
        <!-- /.container -->

    </div>
    <!-- /Sign in -->

    <!-- Sign up -->
    <a  name="signup"></a>
    <div class="content-section-a">

        <div class="container">
            <form action="{% url 'landing:signup' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Sign up</h2>
                    Email: {{form_signup.email}}
                    Contraseña: {{form_signup.password}}
                    Confirmar contraseña: {{form_signup.confirm_password}}
                    <br>
                    <input type="submit" class="btn btn-primary" value="Sign up">
                </div>
            </div>
            </form>
        </div>
        <!-- /.container -->

    </div>
    <!-- /Sign up -->

    <!-- /.content-section-a -->

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Contacto trefi:</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/jonatan-castaneda/trefi" class="btn btn-default btn-lg" target="_blank"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">trefi</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">Nosotros</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Servicios</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contacto</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Trefi 2017. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'landing/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'landing/js/bootstrap.min.js' %}"></script>

</body>

</html>