modules/landing/urls.py
from django.conf.urls import url
from .views import index, dashboard, login, signup, logout

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^dashboard/$', dashboard, name="dashboard"),
    url(r'^login/$', login, name="login"),
    url(r'^signup/$', signup, name="signup"),
    url(r'^logout/$', logout, name="logout"),
]

modules/tracking/urls.py
from django.conf.urls import url
from .views import agregarTransaccion, agregarCuenta, misTransacciones,misCuentas, subirTicket

urlpatterns = [
    url(r'^transaccion/$', agregarTransaccion, name="transaccion"),
    url(r'^nuevacuenta/$', agregarCuenta, name="cuenta"),
    url(r'^transacciones/$', misTransacciones, name="transacciones"),
    url(r'^cuentas/$', misCuentas, name="cuentas"),
    url(r'^ticket/$', subirTicket, name="ticket"),
]

trefi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('modules.landing.urls', namespace="landing")),
    url(r'^educacion/', include('modules.educacion.urls', namespace="educacion")),
    url(r'^', include('modules.tracking.urls', namespace="tracking")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/cuenta.html
{% extends "base_dash.html" %}
{% block title %}
    Cursos
{% endblock title %}

{% block content %}

    <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">
                                Mis cursos
                            </h1>
                            <ol class="breadcrumb">
                                <li>
                                    <i class="fa fa-dashboard"></i>  <a href="{% url 'landing:dashboard' %}">Mi tracking</a>
                                </li>
                                <li class="active">
                                    <i class="fa fa-check-square-o"></i> Cuenta
                                </li>
                            </ol>
                        </div>
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <div class="col-lg-6">
                            <form action="{% url 'tracking:cuenta' %}" method="POST">
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="btn btn-primary">Agregar</button>
                            </form>
                        </div>
                    </div>
                    <!-- /.row -->

                </div>
                <!-- /.container-fluid -->
{% endblock content %}

templates/dashboard/cuentas.html
{% extends "base_dash.html" %}
{% block title %}
    Mis cuentas
{% endblock title %}

{% block content %}

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Mis cuentas
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i>  <a href="{% url 'landing:dashboard' %}">Mi tracking</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-inbox"></i> Mis cuentas
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <h2><i class="fa fa-rocket fa-fw"></i> Ingresos</h2>
            <div class="row">
                {% for cuenta in cuentas %}
                    {% if cuenta.clase_cuenta == "ING" %}
                        <div class="col-lg-3 col-md-6">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-12">
                                            {% for key,value in cuendict.items %}
                                                {% if key == cuenta.tipo_cuenta %}
                                                    <div><h4>{{value}}</h4></div>
                                                {% endif %}
                                            {% endfor %}
                                            <div>Nombre: {{cuenta.nombre}}</div>
                                            <div>Presupuesto: {{cuenta.presupuesto}}</div>
                                            <div>Saldo: {{cuenta.saldo}}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

        <h2><i class="fa fa-inbox fa-fw"></i> Cuentas</h2>
        <div class="row">
            {% for cuenta in cuentas %}
                {% if cuenta.clase_cuenta == "EFE" %}
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-green">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-12">
                                        {% for key,value in cuendict.items %}
                                            {% if key == cuenta.tipo_cuenta %}
                                                <div><h4>{{value}}</h4></div>
                                            {% endif %}
                                        {% endfor %}
                                        <div>Nombre: {{cuenta.nombre}}</div>
                                        <div>Presupuesto: {{cuenta.presupuesto}}</div>
                                        <div>Saldo: {{cuenta.saldo}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        <h2><i class="fa fa-shopping-cart fa-fw"></i> Gastos</h2>
        <div class="row">
            {% for cuenta in cuentas %}
                {% if cuenta.clase_cuenta == "GTO" %}
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-red">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-12">
                                        {% for key,value in cuendict.items %}
                                            {% if key == cuenta.tipo_cuenta %}
                                                <div><h4>{{value}}</h4></div>
                                            {% endif %}
                                        {% endfor %}
                                        <div>Nombre: {{cuenta.nombre}}</div>
                                        <div>Presupuesto: {{cuenta.presupuesto}}</div>
                                        <div>Saldo: {{cuenta.saldo}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        <h2><i class="fa fa-plane fa-fw"></i> Metas</h2>
        <div class="row">
            {% for cuenta in cuentas %}
                {% if cuenta.clase_cuenta == "MTA" %}
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-yellow">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-12">
                                        {% for key,value in cuendict.items %}
                                            {% if key == cuenta.tipo_cuenta %}
                                                <div><h4>{{value}}</h4></div>
                                            {% endif %}
                                        {% endfor %}
                                        <div>Nombre: {{cuenta.nombre}}</div>
                                        <div>Presupuesto: {{cuenta.presupuesto}}</div>
                                        <div>Saldo: {{cuenta.saldo}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <!-- /.row -->

    </div>
                <!-- /.container-fluid -->
{% endblock content %}

templates/dashboard/index.html
{% extends "base_dash.html" %}
{% block title %}
    Mi track
{% endblock title %}

{% block content %}
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Mi tracking personal <small>Resumen de mis finanzas</small>
                </h1>
                <ol class="breadcrumb">
                    <li class="active">
                        <i class="fa fa-dashboard"></i> Mi tracking
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-rocket fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">ingreso</div>
                                <div>{{saldoIngresos}}</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'tracking:cuentas' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver detalle</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-inbox fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">cuentas</div>
                                <div>{{balance}}</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'tracking:cuentas' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver detalle</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-red">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-shopping-cart fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">gastos</div>
                                <div>{{saldoGastos}}</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'tracking:cuentas' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver detalle</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-yellow">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-plane fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">metas</div>
                                <div>{{saldoMetas}}</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'tracking:cuentas' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver detalle</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <!--div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Ingresos y gastos</h3>
                    </div>
                    <div class="panel-body">
                        <div id="morris-area-chart"></div>
                    </div>
                </div>
            </div>
        </div-->
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-flag fa-fw"></i> Ingresos</h3>
                    </div>
                    <div class="panel-body">
                        <div id="morris-donut-chart"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="panel panel-red">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-shopping-cart fa-fw"></i> Resumen de gastos</h3>
                    </div>
                    <div class="panel-body">
                        <div id="morris-donut-chart2"></div>
                        <!--div class="flot-chart">
                            <div class="flot-chart-content" id="flot-pie-chart"></div>
                        </div-->
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-money fa-fw"></i> Resumen de transacciones</h3>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Tipo</th>
                                        <th>De</th>
                                        <th>A</th>
                                        <th>Cantidad</th>
                                        <th>Fecha</th>
                                        <th>Notas</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for transaccion in transacciones %}
                                    <tr>
                                        {% for key,value in transdict.items %}
                                            {% if key == transaccion.clase_trans %}
                                                <td>{{value}}</td>
                                            {% endif %}
                                        {% endfor %}
                                        <td>{{transaccion.de_cuenta}}</td>
                                        <td>{{transaccion.a_cuenta}}</td>
                                        <td>{{transaccion.cantidad}}</td>
                                        <td>{{transaccion.fecha}}</td>
                                        <td>{{transaccion.notas}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="text-right">
                            <a href="{% url 'tracking:transacciones' %}">Ver todas las transacciones <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

    </div>
{% endblock content %}

{% block js %}

    {% autoescape off %}
    <script type="text/javascript">
    // Donut Chart
        Morris.Donut({
            element: 'morris-donut-chart',
            data: {{balancechart}},
            resize: true
        });

        Morris.Donut({
            element: 'morris-donut-chart2',
            data: {{gastoschart}},
            resize: true
        });
        /*  var data = {{dummy}}
          console.log(data)
        Morris.Area({
            element: 'morris-area-chart',
            data: data,
            xkey: 'periodo',
            ykeys: ['Ingreso', 'Gasto'],
            labels: ['Ingreso', 'Gasto'],
            pointSize: 2,
            hideHover: 'auto',
            resize: true
        });
        */


    </script>
    {% endautoescape %}

    <!--script>
        $(function() {

            var data = [{
                label: "Series 0",
                data: 1
            }, {
                label: "Series 1",
                data: 3
            }, {
                label: "Series 2",
                data: 9
            }, {
                label: "Series 3",
                data: 20
            }];

            var plotObj = $.plot($("#flot-pie-chart"), data, {
                series: {
                    pie: {
                        show: true
                    }
                },
                grid: {
                    hoverable: true
                },
                tooltip: true,
                tooltipOpts: {
                    content: "%p.0%, %s", // show percentages, rounding to 2 decimal places
                    shifts: {
                        x: 20,
                        y: 0
                    },
                    defaultTheme: false
                }
            });

        });
    </script-->
{% endblock %}

templates/dashboard/transaccion.html
{% extends "base_dash.html" %}
{% block title %}
    Nueva transacción
{% endblock title %}

{% block content %}

    <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">
                                Nueva transacción
                            </h1>
                            <ol class="breadcrumb">
                                <li>
                                    <i class="fa fa-dashboard"></i>  <a href="{% url 'landing:dashboard' %}">Mi tracking</a>
                                </li>
                                <li class="active">
                                    <i class="fa fa-edit"></i> Transacción
                                </li>
                            </ol>
                        </div>
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <div class="col-lg-6">
                            <form action="{% url 'tracking:ticket' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <label class="btn btn-default btn-file">
                                    {{form_ticket}}
                                </label>
                                <button type="submit" class="btn btn-default"><i class="fa fa-camera"></i> Agregar ticket</button>
                            </form>
                            <form action="{% url 'tracking:transaccion' %}" method="POST">
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="btn btn-primary">Agregar</button>
                                <button type="button" class="btn btn-default"><i class="fa fa-camera"></i> Ticket</button>
                            </form>
                            
                        </div>
                    </div>
                    <!-- /.row -->

                </div>
                <!-- /.container-fluid -->
{% endblock content %}

templates/dashboard/transacciones.html
{% extends "base_dash.html" %}
{% block title %}
    Mis transacciones
{% endblock title %}

{% block content %}

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Mis transacciones
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i>  <a href="{% url 'landing:dashboard' %}">Mi tracking</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-money"></i> Mis Transacciones
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-money fa-fw"></i> Resumen de transacciones</h3>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Tipo</th>
                                        <th>De</th>
                                        <th>A</th>
                                        <th>Cantidad</th>
                                        <th>Fecha</th>
                                        <th>Notas</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for transaccion in transacciones %}
                                    <tr>
                                        {% for key,value in transdict.items %}
                                            {% if key == transaccion.clase_trans %}
                                                <td>{{value}}</td>
                                            {% endif %}
                                        {% endfor %}
                                        <td>{{transaccion.de_cuenta}}</td>
                                        <td>{{transaccion.a_cuenta}}</td>
                                        <td>{{transaccion.cantidad}}</td>
                                        <td>{{transaccion.fecha}}</td>
                                        <td>{{transaccion.notas}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

    </div>
                <!-- /.container-fluid -->
{% endblock content %}